# Generated by Django 5.0.1 on 2026-06-27 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VISIT_REMINDER", "Visit reminder"),
                            ("VISIT_OVERDUE", "Visit overdue"),
                            ("DEVIATION", "Protocol deviation"),
                            ("SCREENING_READY", "Screening ready for review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, default="")),
                ("entity_type", models.CharField(blank=True, default="", max_length=120)),
                ("entity_id", models.CharField(blank=True, default="", max_length=64)),
                ("read", models.BooleanField(default=False)),
                ("dedupe_key", models.CharField(max_length=200, unique=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["recipient", "read"], name="notificatio_recipie_6e3964_idx"
                    )
                ],
            },
        ),
    ]
