# Generated by Django 5.0.1 on 2026-06-27 22:15

import apps.common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("trials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Screening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending ML screening"),
                            ("AWAITING_REVIEW", "Awaiting human review"),
                            ("DECIDED", "Human decision recorded"),
                            ("FAILED", "Screening failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("note_text", apps.common.fields.EncryptedCharField(blank=True, default="")),
                ("ml_score", models.FloatField(blank=True, null=True)),
                (
                    "ml_recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ELIGIBLE", "Eligible"),
                            ("INELIGIBLE", "Ineligible"),
                            ("UNDETERMINED", "Undetermined"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rationale", models.JSONField(blank=True, default=list)),
                ("model_version", models.CharField(blank=True, max_length=64)),
                ("ontology_versions", models.JSONField(blank=True, default=dict)),
                (
                    "human_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ELIGIBLE", "Eligible"),
                            ("INELIGIBLE", "Ineligible"),
                            ("UNDETERMINED", "Undetermined"),
                        ],
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screenings",
                        to="trials.study",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screenings",
                        to="patients.subject",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["status"], name="eligibility_status_66c6c5_idx")],
            },
        ),
    ]
