plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'app/channels/**/*'
    - 'app/mailers/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Gemfile'
    - 'config/routes.rb'

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 10

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120
