function org_som_simple_simpleJUnit(){var T='',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',mb='"><\/script>',bb='#',Jb='&',ac='.cache.html',db='/',pb='//',_b=':',tb='::',ic='<script defer="defer">org_som_simple_simpleJUnit.onInjectionDone(\'org.som.simple.simpleJUnit\')<\/script>',lb='<script id="',wb='=',cb='?',yb='Bad handler "',hc='DOMContentLoaded',$b="GWT module 'org.som.simple.simpleJUnit' may need to be (re)compiled",nb='SCRIPT',Mb='Unexpected exception in locale detection, using default: ',Lb='_',Kb='__gwt_Locale',kb='__gwt_marker_org.som.simple.simpleJUnit',ob='base',gb='baseUrl',X='begin',W='bootstrap',fb='clear.cache.gif',vb='content',Hb='default',ab='end',Ub='gecko',Vb='gecko1_8',Y='gwt.codesvr=',Z='gwt.hosted=',$='gwt.hybrid',bc='gwt/standard/standard.css',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',gc='head',Yb='hosted.html?org_som_simple_simpleJUnit',fc='href',Rb='ie10',Tb='ie8',Sb='ie9',Cb='iframe',eb='img',Db="javascript:''",cc='link',Xb='loadExternalRefs',Gb='locale',Ib='locale=',qb='meta',Fb='moduleRequested',_='moduleStartup',Qb='msie',rb='name',U='org.som.simple.simpleJUnit',ib='org.som.simple.simpleJUnit.nocache.js',sb='org.som.simple.simpleJUnit::',Eb='position:absolute;width:0;height:0;border:none',dc='rel',Pb='safari',hb='script',Zb='selectingPermutation',V='startup',ec='stylesheet',jb='undefined',Wb='unknown',Nb='user.agent',Ob='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=T,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:X});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Y)!=-1||(c.indexOf(Z)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf($)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(U);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return L(a)}}org_som_simple_simpleJUnit=null;c.gwtOnLoad(C,U,t,B);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:ab})}}
function H(){function e(a){var b=a.lastIndexOf(bb);if(b==-1){b=a.length}var c=a.indexOf(cb);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=0?a.substring(0,d+1):T}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(eb);b.src=a+fb;a=e(b.src)}return a}
function g(){var a=K(gb);if(a!=null){return a}return T}
function h(){var a=n.getElementsByTagName(hb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ib)!=-1){return e(a[b].src)}}return T}
function i(){var a;if(typeof isBodyLoaded==jb||!isBodyLoaded()){var b=kb;var c;n.write(lb+b+mb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=nb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return T}
function j(){var a=n.getElementsByTagName(ob);if(a.length>0){return a[a.length-1].href}return T}
function k(){var a=n.location;return a.href==a.protocol+pb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==T){l=h()}if(l==T){l=i()}if(l==T){l=j()}if(l==T&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(qb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(rb),g;if(f){f=f.replace(sb,T);if(f.indexOf(tb)>=0){continue}if(f==ub){g=e.getAttribute(vb);if(g){var h,i=g.indexOf(wb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=T}u[f]=h}}else if(f==xb){g=e.getAttribute(vb);if(g){try{D=eval(g)}catch(a){alert(yb+g+zb)}}}else if(f==Ab){g=e.getAttribute(vb);if(g){try{C=eval(g)}catch(a){alert(yb+g+Bb)}}}}}}
function J(a,b){return b in v[a]}
function K(a){var b=u[a];return b==null?null:b}
function L(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var M;function N(){if(!M){M=true;var a=n.createElement(Cb);a.src=Db;a.id=U;a.style.cssText=Eb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:Fb});a.contentWindow.location.replace(t+P)}}
w[Gb]=function(){var b=null;var c=Hb;try{if(!b){var d=location.search;var e=d.indexOf(Ib);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Jb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=K(Gb)}if(!b){b=m[Kb]}if(b){c=b}while(b&&!J(Gb,b)){var h=b.lastIndexOf(Lb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Mb+a)}m[Kb]=c;return b||Hb};v[Gb]={'default':0,fr:1};w[Nb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Ob)!=-1}())return Pb;if(function(){return b.indexOf(Qb)!=-1&&n.documentMode>=10}())return Rb;if(function(){return b.indexOf(Qb)!=-1&&n.documentMode>=9}())return Sb;if(function(){return b.indexOf(Qb)!=-1&&n.documentMode>=8}())return Tb;if(function(){return b.indexOf(Ub)!=-1}())return Vb;return Wb};v[Nb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};org_som_simple_simpleJUnit.onScriptLoad=function(){if(M){r=true;G()}};org_som_simple_simpleJUnit.onInjectionDone=function(){q=true;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Xb,millis:(new Date).getTime(),type:ab});G()};I();H();var O;var P;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(U))){m.location.reload();return}P=Yb;O=T}o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:Zb});if(!F()){try{alert($b);return;var Q=O.indexOf(_b);if(Q!=-1){B=Number(O.substring(Q+1));O=O.substring(0,Q)}P=O+ac}catch(a){return}}var R;function S(){if(!s){s=true;if(!__gwt_stylesLoaded[bc]){var a=n.createElement(cc);__gwt_stylesLoaded[bc]=a;a.setAttribute(dc,ec);a.setAttribute(fc,t+bc);n.getElementsByTagName(gc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(hc,S,false)}if(R){clearInterval(R)}}}
if(n.addEventListener){n.addEventListener(hc,function(){N();S()},false)}var R=setInterval(function(){if(/loaded|complete/.test(n.readyState)){N();S()}},50);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:ab});o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Xb,millis:(new Date).getTime(),type:X});n.write(ic)}
org_som_simple_simpleJUnit();