apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: replicas.yaml
images:
  - { name: inventory-backend, newTag: production }
  - { name: inventory-frontend, newTag: production }
  - { name: inventory-forecast, newTag: production }

