version: 2
updates:
  - package-ecosystem: maven
    directory: /services/order-service
    schedule:
      interval: weekly
    groups:
      spring:
        patterns: ["org.springframework*"]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /services/order-service
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /tools/risk-score
    schedule:
      interval: monthly
