plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  Exclude:
    - "vendor/**/*"
    - "build/**/*"

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/YAMLFileRead:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - "spec/**/*"
    - "Rakefile"

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Lint/RedundantDirGlobSort:
  Enabled: false

Lint/RedundantRequireStatement:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

Style/ComparableClamp:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/HashExcept:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MapToSet:
  Enabled: false

Style/OneClassPerFile:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantSort:
  Enabled: false

Style/ReduceToHash:
  Enabled: false

Style/SelectByRegexp:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false
