version: "3.8"

services:
  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - "4566:4566" # LocalStack Endpoint
      - "4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:4566/restapis/mock/prod/_user_request_
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - localstack
