# Generated by Django 5.2.10 on 2026-01-29 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=50)),
                ("algorithm", models.CharField(max_length=50)),
                ("model_path", models.CharField(max_length=500)),
                ("training_samples", models.PositiveIntegerField(default=0)),
                ("training_loss", models.FloatField(blank=True, null=True)),
                ("validation_loss", models.FloatField(blank=True, null=True)),
                ("precision_at_k", models.FloatField(blank=True, null=True)),
                ("recall_at_k", models.FloatField(blank=True, null=True)),
                ("ndcg_at_k", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "recommendation model",
                "verbose_name_plural": "recommendation models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField()),
                (
                    "algorithm",
                    models.CharField(default="collaborative_filtering", max_length=50),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities",
                        to="products.product",
                    ),
                ),
                (
                    "similar_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_similarities",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product similarity",
                "verbose_name_plural": "product similarities",
                "ordering": ["-similarity_score"],
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("cart", "Added to Cart"),
                            ("purchase", "Purchased"),
                            ("wishlist", "Added to Wishlist"),
                            ("review", "Reviewed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("implicit_rating", models.FloatField(default=1.0)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "user interaction",
                "verbose_name_plural": "user interactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
