# Generated by Django 5.2.10 on 2026-01-29 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productsimilarity",
            unique_together={("product", "similar_product", "algorithm")},
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["user", "product"], name="recommendat_user_id_44f668_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteraction",
            index=models.Index(
                fields=["interaction_type", "created_at"],
                name="recommendat_interac_1901bd_idx",
            ),
        ),
    ]
