## YAML Template.
---
# Eureka settings
eureka:
   client:
      serviceUrl:
         # For a clustered Eureka setup
         # defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
         # For a standalone Eureka instance
         defaultZone: http://localhost:8010/eureka/
