# Generated by Django 5.0.1 on 2026-06-27 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("READ", "Read (sensitive)"),
                            ("LOGIN", "Login"),
                            ("ESIGN", "Electronic signature"),
                            ("ML_SCREEN", "ML eligibility screening"),
                            ("DECISION", "Human eligibility decision"),
                        ],
                        max_length=16,
                    ),
                ),
                ("correlation_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("entity_type", models.CharField(db_index=True, max_length=120)),
                ("entity_id", models.CharField(db_index=True, max_length=64)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("prev_hash", models.CharField(blank=True, max_length=64)),
                ("row_hash", models.CharField(blank=True, max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "created_at"],
                        name="audit_audit_entity__73f5bf_idx",
                    )
                ],
            },
        ),
    ]
