# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Programs/jdk-17.0.1

# Allow APK to be installed directly on phones via file manager (removes testOnly restriction)
android.injected.testOnly=false

# AndroidX package structure
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true