apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drug-interaction-checker

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - ml-deployment.yaml
  - ml-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: drug-interaction-checker
