/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_parallelimage_nativebridge_NativeImageEnhancer */

#ifndef _Included_com_parallelimage_nativebridge_NativeImageEnhancer
#define _Included_com_parallelimage_nativebridge_NativeImageEnhancer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_parallelimage_nativebridge_NativeImageEnhancer_API_VERSION
#define com_parallelimage_nativebridge_NativeImageEnhancer_API_VERSION 1L
#undef com_parallelimage_nativebridge_NativeImageEnhancer_CODE_CLAHE
#define com_parallelimage_nativebridge_NativeImageEnhancer_CODE_CLAHE 1L
#undef com_parallelimage_nativebridge_NativeImageEnhancer_CODE_DENOISE
#define com_parallelimage_nativebridge_NativeImageEnhancer_CODE_DENOISE 2L
#undef com_parallelimage_nativebridge_NativeImageEnhancer_CODE_SUPER_RESOLUTION
#define com_parallelimage_nativebridge_NativeImageEnhancer_CODE_SUPER_RESOLUTION 3L
#undef com_parallelimage_nativebridge_NativeImageEnhancer_BYTES_PER_PIXEL
#define com_parallelimage_nativebridge_NativeImageEnhancer_BYTES_PER_PIXEL 4L
/*
 * Class:     com_parallelimage_nativebridge_NativeImageEnhancer
 * Method:    nativeApiVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_parallelimage_nativebridge_NativeImageEnhancer_nativeApiVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_parallelimage_nativebridge_NativeImageEnhancer
 * Method:    nativeDescribe
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_parallelimage_nativebridge_NativeImageEnhancer_nativeDescribe
  (JNIEnv *, jclass);

/*
 * Class:     com_parallelimage_nativebridge_NativeImageEnhancer
 * Method:    nativeSupports
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_parallelimage_nativebridge_NativeImageEnhancer_nativeSupports
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_parallelimage_nativebridge_NativeImageEnhancer
 * Method:    nativeLoadModel
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_parallelimage_nativebridge_NativeImageEnhancer_nativeLoadModel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_parallelimage_nativebridge_NativeImageEnhancer
 * Method:    nativeEnhance
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIID)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_parallelimage_nativebridge_NativeImageEnhancer_nativeEnhance
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
