FROM node:18-alpine

WORKDIR /app
COPY package.json ./
RUN npm install && apk add --no-cache curl
COPY hardhat.config.js ./
COPY contracts/ contracts/
COPY scripts/ scripts/
COPY ignition/ ignition/

EXPOSE 8545
RUN chmod +x scripts/entrypoint.sh
CMD ["sh", "scripts/entrypoint.sh"]
