"""Subject API — CRUD with system-generated subject codes."""
from __future__ import annotations

from rest_framework.decorators import action
from rest_framework.response import Response

from apps.common.viewsets import BaseModelViewSet

from . import services
from .models import Subject
from .serializers import SubjectSerializer


class SubjectViewSet(BaseModelViewSet):
    serializer_class = SubjectSerializer
    queryset = Subject.objects.all()

    def get_queryset(self):
        qs = Subject.objects.all()
        code = self.request.query_params.get("subject_code")
        if code:
            qs = qs.filter(subject_code__iexact=code)
        return qs

    def perform_create(self, serializer) -> None:
        # subject_code is generated by the service, not supplied by the client.
        subject = services.create_subject(
            created_by=self.request.user,
            **{k: v for k, v in serializer.validated_data.items() if k != "subject_code"},
        )
        serializer.instance = subject

    @action(detail=True, methods=["get"])
    def deidentified(self, request, public_id=None) -> Response:
        """GET .../deidentified/ — the PHI-free view used by ML/analytics."""
        return Response(services.deidentify(self.get_object()))
