apiVersion: v1
kind: Service
metadata:
  name: inventory-backend
  namespace: inventory
spec:
  selector:
    app.kubernetes.io/name: inventory-backend
  ports:
    - { name: http, port: 8080, targetPort: http }

