apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inventory
resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - forecast-deployment.yaml
  - forecast-service.yaml
  - ingress.yaml
  - hpa.yaml
  - pod-disruption-budget.yaml
  - network-policy.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
