apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inventory-backend
  namespace: inventory
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inventory-frontend
  namespace: inventory
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inventory-forecast
  namespace: inventory
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-forecast
