app = "url-shortener-service"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  HTTP_ADDR = ":8080"
  GIN_MODE = "release"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

