FROM openjdk:11

COPY target/interview-16-02-preparing-boot-data-h2-0.0.1-SNAPSHOT.jar /usr/app/

WORKDIR /usr/app

ENTRYPOINT ["java", "-jar", "interview-16-02-preparing-boot-data-h2-0.0.1-SNAPSHOT.jar"]