/// **The validation boundary.**
///
/// This is the local-first equivalent of an HTTP controller (PROJECT-PLAN §0
/// "Deliverable mapping note"): it is the last place that can reject bad data
/// before it becomes persistent, and it is written to that standard — validate
/// everything, trust nothing, return typed failures instead of throwing.
///
/// Nothing above this layer knows how expenses are stored or partitioned, which
/// is what makes the year-partitioning plan in ARCHITECTURE §2.4 a one-file
/// change.
library;

import 'package:flutter/foundation.dart' show ValueListenable;
import 'package:hive_flutter/hive_flutter.dart';
import 'package:uuid/uuid.dart';

import '../../core/error/failures.dart';
import '../../core/logging/app_logger.dart';
import '../../core/utils/date_range.dart';
import '../../core/utils/money.dart';
import '../../core/utils/result.dart';
import '../datasources/hive_service.dart';
import '../models/expense.dart';

/// Unvalidated user input. Kept separate from [Expense] so an invalid draft can
/// exist in the UI without an invalid [Expense] ever existing in the type system.
class ExpenseDraft {
  const ExpenseDraft({
    required this.amountInput,
    required this.currencyCode,
    required this.categoryId,
    required this.date,
    this.note,
    this.id,
    this.recurringId,
  });

  /// Raw text as typed, e.g. `"12,50"`. Parsed and validated here, not in the UI.
  final String amountInput;
  final String currencyCode;
  final String categoryId;
  final DateTime date;
  final String? note;

  /// Non-null when editing an existing expense.
  final String? id;
  final String? recurringId;
}

class ExpenseRepository {
  ExpenseRepository(this._hive, {Uuid? uuid}) : _uuid = uuid ?? const Uuid();

  final HiveService _hive;
  final Uuid _uuid;
  final AppLogger _log = AppLogger('ExpenseRepository');

  static const int _maxNoteLength = 500;

  /// Reject dates absurdly far out — a fat-fingered year (2207) would otherwise
  /// silently vanish from every report.
  static const Duration _maxFutureDate = Duration(days: 366);

  Box<Expense> get _box => _hive.expenses;

  /// For `ValueListenableBuilder` — lets the UI react to writes without the
  /// Provider having to re-read the whole box.
  ValueListenable<Box<Expense>> listenable() => _box.listenable();

  // -------------------------------------------------------------------------
  // Reads
  // -------------------------------------------------------------------------

  Result<Expense> getById(String id) {
    final found = _box.get(id);
    if (found == null) {
      return Err(NotFoundFailure('Expense not found', id: id));
    }
    return Ok(found);
  }

  /// All expenses, newest first.
  List<Expense> all() {
    final items = _box.values.toList(growable: false)
      ..sort((a, b) => b.date.compareTo(a.date));
    return items;
  }

  /// Expenses within `[range.start, range.end)`, newest first.
  ///
  /// O(n) over an in-memory box. Sub-millisecond below ~20k records; beyond that
  /// see the partitioning plan in ARCHITECTURE §2.4 — which changes only this
  /// method.
  List<Expense> byDateRange(DateRange range) {
    final items = <Expense>[];
    for (final e in _box.values) {
      if (range.contains(e.date)) items.add(e);
    }
    items.sort((a, b) => b.date.compareTo(a.date));
    return items;
  }

  List<Expense> byMonth(DateTime anchor) => byDateRange(DateRange.month(anchor));

  List<Expense> byCategory(String categoryId, {DateRange? within}) {
    return _box.values
        .where((e) => e.categoryId == categoryId)
        .where((e) => within == null || within.contains(e.date))
        .toList(growable: false);
  }

  /// Expenses generated by a given recurrence — used when a recurrence is
  /// deleted and the user opts to remove its generated rows too.
  List<Expense> byRecurringId(String recurringId) =>
      _box.values.where((e) => e.recurringId == recurringId).toList(growable: false);

  int get count => _box.length;

  /// Distinct currencies in use — drives which FX rates need fetching.
  Set<String> currenciesInUse() =>
      _box.values.map((e) => e.currencyCode).toSet();

  // -------------------------------------------------------------------------
  // Writes
  // -------------------------------------------------------------------------

  /// Validates [draft] and persists a new expense.
  Future<Result<Expense>> create(ExpenseDraft draft) async {
    final validated = _validate(draft);
    if (validated case Err<Money>(:final failure)) return Err(failure);
    final amount = (validated as Ok<Money>).value;

    final now = DateTime.now();
    final expense = Expense(
      id: draft.id ?? _uuid.v4(),
      amountMinor: amount.minorUnits,
      currencyCode: amount.currencyCode,
      categoryId: draft.categoryId,
      date: dateOnly(draft.date),
      createdAt: now,
      note: _normaliseNote(draft.note),
      recurringId: draft.recurringId,
    );

    try {
      await _box.put(expense.id, expense);
      // Amount is redacted: it is the most sensitive value we hold (§2.6).
      _log.info('expense created', {
        'id': expense.id,
        'amount': AppLogger.redact(expense.amount.formatted),
      });
      return Ok(expense);
    } catch (error, stack) {
      _log.error('expense write failed', cause: error, stackTrace: stack, fields: {
        'id': expense.id,
      });
      return Err(StorageFailure('Could not save expense', cause: error, stackTrace: stack));
    }
  }

  /// Updates an existing expense. Fails if [ExpenseDraft.id] is absent or unknown
  /// rather than silently creating a new row.
  Future<Result<Expense>> update(ExpenseDraft draft) async {
    final id = draft.id;
    if (id == null) {
      return const Err(ValidationFailure('Cannot update an expense without an id'));
    }
    final existing = _box.get(id);
    if (existing == null) {
      return Err(NotFoundFailure('Expense not found', id: id));
    }

    final validated = _validate(draft);
    if (validated case Err<Money>(:final failure)) return Err(failure);
    final amount = (validated as Ok<Money>).value;

    final updated = Expense(
      id: id,
      amountMinor: amount.minorUnits,
      currencyCode: amount.currencyCode,
      categoryId: draft.categoryId,
      date: dateOnly(draft.date),
      createdAt: existing.createdAt,
      note: _normaliseNote(draft.note),
      recurringId: existing.recurringId,
    );

    try {
      await _box.put(id, updated);
      return Ok(updated);
    } catch (error, stack) {
      return Err(StorageFailure('Could not update expense', cause: error, stackTrace: stack));
    }
  }

  Future<Result<void>> delete(String id) async {
    if (!_box.containsKey(id)) {
      return Err(NotFoundFailure('Expense not found', id: id));
    }
    try {
      await _box.delete(id);
      _log.info('expense deleted', {'id': id});
      return okVoid;
    } catch (error, stack) {
      return Err(StorageFailure('Could not delete expense', cause: error, stackTrace: stack));
    }
  }

  /// Batch insert — used by recurring materialisation. One `putAll` rather than N
  /// `put`s, so a six-week catch-up is a single write.
  Future<Result<int>> createMany(List<Expense> expenses) async {
    if (expenses.isEmpty) return const Ok(0);
    try {
      await _box.putAll({for (final e in expenses) e.id: e});
      _log.info('batch insert', {'count': expenses.length});
      return Ok(expenses.length);
    } catch (error, stack) {
      return Err(StorageFailure('Could not save generated expenses',
          cause: error, stackTrace: stack));
    }
  }

  Future<Result<int>> deleteByRecurringId(String recurringId) async {
    final ids = byRecurringId(recurringId).map((e) => e.id).toList();
    if (ids.isEmpty) return const Ok(0);
    try {
      await _box.deleteAll(ids);
      return Ok(ids.length);
    } catch (error, stack) {
      return Err(StorageFailure('Could not delete generated expenses',
          cause: error, stackTrace: stack));
    }
  }

  // -------------------------------------------------------------------------
  // Validation — the whole reason this class exists
  // -------------------------------------------------------------------------

  Result<Money> _validate(ExpenseDraft draft) {
    // 1. Amount must parse. Bad input is a ValidationFailure with a field name so
    //    the UI can attach it to the right control, not a generic banner.
    final Money amount;
    try {
      amount = Money.parse(draft.amountInput, draft.currencyCode);
    } on MoneyFormatException {
      return const Err(ValidationFailure(
        'Enter a valid amount, for example 12.50',
        field: 'amount',
      ));
    } on ArgumentError {
      return const Err(ValidationFailure(
        'Unknown currency code',
        field: 'currency',
      ));
    }

    // 2. Zero and negative are rejected. A refund is a separate concept; letting
    //    negatives in here makes every budget calculation ambiguous.
    if (!amount.isPositive) {
      return const Err(ValidationFailure(
        'Amount must be greater than zero',
        field: 'amount',
      ));
    }

    // 3. Sanity ceiling — catches a missed decimal point (1250000 vs 12.50).
    if (amount.minorUnits > 999999999999) {
      return const Err(ValidationFailure('That amount is too large', field: 'amount'));
    }

    // 4. Category must exist. A dangling categoryId would make the expense
    //    invisible in every category breakdown — a silent data loss.
    if (draft.categoryId.isEmpty || !_hive.categories.containsKey(draft.categoryId)) {
      return const Err(ValidationFailure('Choose a category', field: 'category'));
    }

    // 5. Date sanity.
    final now = DateTime.now();
    if (draft.date.isAfter(now.add(_maxFutureDate))) {
      return const Err(ValidationFailure(
        'That date is too far in the future',
        field: 'date',
      ));
    }
    if (draft.date.year < 1970) {
      return const Err(ValidationFailure('That date is not valid', field: 'date'));
    }

    // 6. Note length — unbounded text would bloat the box and the CSV export.
    if ((draft.note?.length ?? 0) > _maxNoteLength) {
      return const Err(ValidationFailure(
        'Note is too long (max $_maxNoteLength characters)',
        field: 'note',
      ));
    }

    return Ok(amount);
  }

  String? _normaliseNote(String? note) {
    final trimmed = note?.trim();
    return (trimmed == null || trimmed.isEmpty) ? null : trimmed;
  }
}
