# Generated by Django 5.2.10 on 2026-01-29 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="inventory_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("product", "variant")},
        ),
    ]
