logging:
  level: INFO
  loggers:
    org.example: DEBUG

template: Hello, %s!
defaultName: Stranger

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8082