# Generated by Django 5.0.1 on 2026-06-27 22:15

import apps.common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("subject_code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("first_name", apps.common.fields.EncryptedCharField(blank=True, default="")),
                ("last_name", apps.common.fields.EncryptedCharField(blank=True, default="")),
                (
                    "medical_record_number",
                    apps.common.fields.EncryptedCharField(blank=True, default=""),
                ),
                ("date_of_birth", apps.common.fields.EncryptedCharField(blank=True, default="")),
                ("sex_at_birth", models.CharField(blank=True, default="", max_length=16)),
                ("enrolled", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subject",
                "ordering": ("subject_code",),
            },
        ),
    ]
