variable "name" {
  type        = string
  description = "Flexible server name, e.g. psql-fraud-dev."
}

variable "resource_group_name" {
  type        = string
  description = "Resource group in which to create the server."
}

variable "location" {
  type        = string
  description = "Azure region."
}

variable "postgres_version" {
  type        = string
  description = "Major PostgreSQL version."
  default     = "16"
}

variable "administrator_login" {
  type        = string
  description = "Admin login name for the flexible server."
}

variable "administrator_password" {
  type        = string
  description = "Admin password. Generated by the root module; never commit real values."
  sensitive   = true
}

variable "sku_name" {
  type        = string
  description = "Flexible server SKU, e.g. B_Standard_B1ms or GP_Standard_D4s_v3."
}

variable "storage_mb" {
  type        = number
  description = "Storage size in MB (minimum 32768)."
}

variable "database_name" {
  type        = string
  description = "Application database name."
  default     = "fraud"
}

variable "tags" {
  type        = map(string)
  description = "Tags applied to the server."
  default     = {}
}
