## YAML Template.
---
spring:
  application:
      name: lab06-feign
      
# Eureka settings
eureka:
   client:
      serviceUrl:
         # defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/y
         defaultZone: http://localhost:8010/eureka/
         
server:
    port: 8181   # Select any available port if neither port nor server port are specified.         
         
