-- V1: Patient search index + raw FHIR resource store (owned by fhir-gateway-service).
CREATE TABLE PATIENT_INDEX (
    FHIR_ID           VARCHAR2(64)   NOT NULL,
    IDENTIFIER_SYSTEM VARCHAR2(256),
    IDENTIFIER_VALUE  VARCHAR2(256),
    FAMILY_NAME       VARCHAR2(256),
    GIVEN_NAME        VARCHAR2(256),
    BIRTH_DATE        DATE,
    RESOURCE_JSON     CLOB,
    LAST_UPDATED      TIMESTAMP      NOT NULL,
    VERSION           NUMBER(19)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PATIENT_INDEX PRIMARY KEY (FHIR_ID)
);

CREATE INDEX IX_PATIENT_IDENTIFIER ON PATIENT_INDEX (IDENTIFIER_SYSTEM, IDENTIFIER_VALUE);
CREATE INDEX IX_PATIENT_FAMILY ON PATIENT_INDEX (FAMILY_NAME);
