-- V2: Transactional outbox (Kafka relay) + append-only PHI audit (HIPAA).

CREATE TABLE OUTBOX_EVENT (
    EVENT_ID       VARCHAR2(64)  NOT NULL,
    EVENT_TYPE     VARCHAR2(128) NOT NULL,
    RESOURCE_TYPE  VARCHAR2(64)  NOT NULL,
    RESOURCE_ID    VARCHAR2(64)  NOT NULL,
    PAYLOAD_JSON   CLOB          NOT NULL,
    CREATED_AT     TIMESTAMP     NOT NULL,
    SENT_AT        TIMESTAMP,
    CONSTRAINT PK_OUTBOX_EVENT PRIMARY KEY (EVENT_ID)
);
CREATE INDEX IX_OUTBOX_UNSENT ON OUTBOX_EVENT (SENT_AT, CREATED_AT);

CREATE TABLE PHI_AUDIT (
    AUDIT_ID       VARCHAR2(64)  NOT NULL,
    ACTOR_ID       VARCHAR2(256) NOT NULL,
    ACTION         VARCHAR2(32)  NOT NULL,
    RESOURCE_TYPE  VARCHAR2(64)  NOT NULL,
    RESOURCE_ID    VARCHAR2(64),
    PURPOSE_OF_USE VARCHAR2(64),
    SOURCE_IP      VARCHAR2(64),
    OCCURRED_AT    TIMESTAMP     NOT NULL,
    TRACE_ID       VARCHAR2(64),
    CONSTRAINT PK_PHI_AUDIT PRIMARY KEY (AUDIT_ID)
);
CREATE INDEX IX_AUDIT_RESOURCE ON PHI_AUDIT (RESOURCE_TYPE, RESOURCE_ID);
CREATE INDEX IX_AUDIT_ACTOR ON PHI_AUDIT (ACTOR_ID, OCCURRED_AT);
