source "https://rubygems.org"

ruby ">= 3.3.0", "< 3.4"

gem "bootsnap", require: false
gem "bcrypt"
gem "graphql"
gem "jwt"
gem "pg"
gem "puma"
gem "rack-cors"
gem "rails", "~> 7.1.0"
gem "redis"
gem "sidekiq"

group :development, :test do
  gem "factory_bot_rails"
  gem "rspec-rails"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end

group :test do
  gem "faker"
  gem "simplecov", require: false
end
