from __future__ import annotations

from dp_algorithms import (
    climbing_stairs,
    coin_change,
    edit_distance,
    egg_drop,
    equal_partition,
    fibonacci,
    house_robber,
    knapsack,
    lcs,
    lis,
    longest_common_substring,
    longest_palindrome,
    longest_palindromic_subsequence,
    matrix_chain,
    minimum_path_sum,
    optimal_bst,
    rod_cutting,
    subset_sum,
    tsp,
    unique_paths,
    word_break,
)


def run() -> None:
    examples = [
        knapsack.memoized([2, 3, 4, 5], [3, 4, 5, 8], 8),
        knapsack.tabulated([2, 3, 4, 5], [3, 4, 5, 8], 8),
        knapsack.space_optimized([2, 3, 4, 5], [3, 4, 5, 8], 8),
        lcs.memoized("AGGTAB", "GXTXAYB"),
        lcs.tabulated("AGGTAB", "GXTXAYB"),
        lcs.space_optimized("AGGTAB", "GXTXAYB"),
        lis.memoized([10, 9, 2, 5, 3, 7, 101, 18]),
        lis.tabulated([10, 9, 2, 5, 3, 7, 101, 18]),
        lis.space_optimized([10, 9, 2, 5, 3, 7, 101, 18]),
        edit_distance.memoized("kitten", "sitting"),
        edit_distance.tabulated("kitten", "sitting"),
        edit_distance.space_optimized("kitten", "sitting"),
        matrix_chain.memoized([40, 20, 30, 10, 30]),
        matrix_chain.tabulated([40, 20, 30, 10, 30]),
        matrix_chain.space_optimized([40, 20, 30, 10, 30]),
        coin_change.memoized([1, 3, 4], 6),
        coin_change.tabulated([1, 3, 4], 6),
        coin_change.space_optimized([1, 3, 4], 6),
        rod_cutting.memoized([1, 5, 8, 9, 10, 17, 17, 20], 8),
        rod_cutting.tabulated([1, 5, 8, 9, 10, 17, 17, 20], 8),
        rod_cutting.space_optimized([1, 5, 8, 9, 10, 17, 17, 20], 8),
        longest_palindrome.memoized("babad"),
        longest_palindrome.tabulated("babad"),
        longest_palindrome.space_optimized("babad"),
        egg_drop.memoized(2, 10),
        egg_drop.tabulated(2, 10),
        egg_drop.space_optimized(2, 10),
        optimal_bst.memoized(["A", "B", "C"], [34, 8, 50]),
        optimal_bst.tabulated(["A", "B", "C"], [34, 8, 50]),
        optimal_bst.space_optimized(["A", "B", "C"], [34, 8, 50]),
        tsp.memoized([[0, 10, 15, 20], [10, 0, 35, 25], [15, 35, 0, 30], [20, 25, 30, 0]]),
        tsp.tabulated([[0, 10, 15, 20], [10, 0, 35, 25], [15, 35, 0, 30], [20, 25, 30, 0]]),
        tsp.space_optimized([[0, 10, 15, 20], [10, 0, 35, 25], [15, 35, 0, 30], [20, 25, 30, 0]]),
        fibonacci.memoized(10),
        fibonacci.tabulated(10),
        fibonacci.space_optimized(10),
        climbing_stairs.memoized(5),
        climbing_stairs.tabulated(5),
        climbing_stairs.space_optimized(5),
        unique_paths.memoized(3, 7),
        unique_paths.tabulated(3, 7),
        unique_paths.space_optimized(3, 7),
        minimum_path_sum.memoized([[1, 3, 1], [1, 5, 1], [4, 2, 1]]),
        minimum_path_sum.tabulated([[1, 3, 1], [1, 5, 1], [4, 2, 1]]),
        minimum_path_sum.space_optimized([[1, 3, 1], [1, 5, 1], [4, 2, 1]]),
        subset_sum.memoized([3, 34, 4, 12, 5, 2], 9),
        subset_sum.tabulated([3, 34, 4, 12, 5, 2], 9),
        subset_sum.space_optimized([3, 34, 4, 12, 5, 2], 9),
        equal_partition.memoized([1, 5, 11, 5]),
        equal_partition.tabulated([1, 5, 11, 5]),
        equal_partition.space_optimized([1, 5, 11, 5]),
        longest_common_substring.memoized("ABABC", "BABCA"),
        longest_common_substring.tabulated("ABABC", "BABCA"),
        longest_common_substring.space_optimized("ABABC", "BABCA"),
        longest_palindromic_subsequence.memoized("bbbab"),
        longest_palindromic_subsequence.tabulated("bbbab"),
        longest_palindromic_subsequence.space_optimized("bbbab"),
        word_break.memoized("leetcode", {"leet", "code"}),
        word_break.tabulated("leetcode", {"leet", "code"}),
        word_break.space_optimized("leetcode", {"leet", "code"}),
        house_robber.memoized([2, 7, 9, 3, 1]),
        house_robber.tabulated([2, 7, 9, 3, 1]),
        house_robber.space_optimized([2, 7, 9, 3, 1]),
    ]
    print("Dynamic Programming Demo")
    print("=" * 28)
    for result in examples:
        print(result.describe())


if __name__ == "__main__":
    run()
