package com.ap.wsdl2javagenerated;

import com.ap.services.*;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2016-05-08T01:08:45.944+03:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "DateServiceImplService", 
                  wsdlLocation = "http://localhost:8080/codegeekap/services/dateservice?wsdl",
                  targetNamespace = "http://services.ap.com/") 
public class DateServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.ap.com/", "DateServiceImplService");
    public final static QName DateServiceImplPort = new QName("http://services.ap.com/", "DateServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/codegeekap/services/dateservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DateServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/codegeekap/services/dateservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DateServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DateServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DateServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DateServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DateServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DateServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DateService
     */
    @WebEndpoint(name = "DateServiceImplPort")
    public com.ap.services.DateService getDateServiceImplPort() {
        return super.getPort(DateServiceImplPort, com.ap.services.DateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DateService
     */
    @WebEndpoint(name = "DateServiceImplPort")
    public com.ap.services.DateService getDateServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DateServiceImplPort, com.ap.services.DateService.class, features);
    }

}
