package com.ap.wsdl2javagenerated;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2016-05-08T01:08:45.848+03:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://services.ap.com/", name = "DateService")
@XmlSeeAlso({ObjectFactory.class})
public interface DateService {

    @WebMethod
    @RequestWrapper(localName = "getDate", targetNamespace = "http://services.ap.com/", className = "com.ap.services.GetDate")
    @ResponseWrapper(localName = "getDateResponse", targetNamespace = "http://services.ap.com/", className = "com.ap.services.GetDateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getDate(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0
    );
}
