apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invoice-factoring-dev

resources:
  - ../../base

# CD patches newTag to the built image's git SHA.
images:
  - name: invfactacr.azurecr.io/invoice-factoring-api
    newTag: dev-latest
  - name: invfactacr.azurecr.io/invoice-factoring-frontend
    newTag: dev-latest

replicas:
  - name: api
    count: 1
  - name: frontend
    count: 1
