name: indoor_mapping_app
description: Flutter indoor mapping and navigation app.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  mapbox_maps_flutter: ^2.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
