// ============================================================================
//  pip_enhance.cpp — the OpenCV side of the ImageEnhancer SPI.
//
//  This file is the only C++ in the project, and it is written defensively on
//  purpose. Everything above it can throw an exception and be caught; a mistake
//  here is a segfault, which is not a stack trace but a dead JVM and a user with
//  no idea which of their 4 000 photographs did it. So:
//
//    * every argument from Java is validated, never trusted;
//    * every OpenCV call is inside a try/catch for cv::Exception;
//    * nothing throws across the JNI boundary — failure is a null return, which
//      NativeImageEnhancer.enhance() documents as "pass the image through";
//    * no global mutable state except the one lazily-loaded model, guarded.
//
//  Build: see CMakeLists.txt in this directory. The header is generated by javac
//  (pip-native/pom.xml passes -h) and must not be hand-edited.
// ============================================================================

#include "com_parallelimage_nativebridge_NativeImageEnhancer.h"

#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/photo.hpp>

#ifdef PIP_WITH_DNN_SUPERRES
#include <opencv2/dnn_superres.hpp>
#endif

#include <cstdint>
#include <cstring>
#include <mutex>
#include <string>
#include <vector>

namespace {

// Must match the CODE_* constants in NativeImageEnhancer. Never renumber.
constexpr jint kCodeClahe = 1;
constexpr jint kCodeDenoise = 2;
constexpr jint kCodeSuperResolution = 3;

// Must match NativeImageEnhancer.API_VERSION. Bump both together whenever a
// signature or a mode code changes.
constexpr jint kApiVersion = 1;

// A 24-megapixel image is ~24e6 pixels; the cap is generous but finite, because
// width * height is computed as int64 and then used to size a cv::Mat, and a
// hostile or corrupt caller passing INT_MAX for both would overflow the
// allocation size on the way in.
constexpr int64_t kMaxPixels = 500LL * 1000LL * 1000LL;

std::once_flag g_model_once;
bool g_model_ready = false;

#ifdef PIP_WITH_DNN_SUPERRES
cv::dnn_superres::DnnSuperResImpl g_super_res;
#endif

/// Wraps a raw pointer into a direct ByteBuffer's memory in a cv::Mat with no copy.
///
/// CV_8UC4 over the same memory as the packed ints: OpenCV's channel order for
/// this layout on a little-endian machine is B,G,R,A, which is what the
/// component order of a Java 0xAARRGGBB int looks like read byte by byte. That
/// coincidence is why no per-pixel shuffle is needed here — and why this code is
/// wrong on a big-endian JVM, of which there are no supported builds.
cv::Mat wrapArgb(jint* pixels, int width, int height) {
    return cv::Mat(height, width, CV_8UC4, static_cast<void*>(pixels));
}

/// CLAHE on the L channel of Lab, blended back by `strength`.
///
/// Lab rather than RGB: equalising the three colour channels independently
/// shifts hue, and a photograph that comes back with a green cast is worse than
/// one that came back untouched.
bool applyClahe(const cv::Mat& bgra, cv::Mat& out, double strength) {
    cv::Mat bgr;
    cv::cvtColor(bgra, bgr, cv::COLOR_BGRA2BGR);

    cv::Mat lab;
    cv::cvtColor(bgr, lab, cv::COLOR_BGR2Lab);

    std::vector<cv::Mat> planes;
    cv::split(lab, planes);

    // clipLimit scales with strength: 1.0 is a no-op, 4.0 is aggressive.
    const double clip_limit = 1.0 + 3.0 * strength;
    cv::Ptr<cv::CLAHE> clahe = cv::createCLAHE(clip_limit, cv::Size(8, 8));
    cv::Mat equalised;
    clahe->apply(planes[0], equalised);
    planes[0] = equalised;

    cv::merge(planes, lab);
    cv::Mat enhanced_bgr;
    cv::cvtColor(lab, enhanced_bgr, cv::COLOR_Lab2BGR);

    // Blend, so `strength` is continuous rather than a switch. Without this a
    // strength of 0.1 and 0.9 would look identical apart from the clip limit.
    cv::Mat blended;
    cv::addWeighted(enhanced_bgr, strength, bgr, 1.0 - strength, 0.0, blended);

    cv::cvtColor(blended, out, cv::COLOR_BGR2BGRA);
    return true;
}

/// Non-local-means denoise. h scales with strength; 3 and 21 are the values
/// OpenCV's own documentation recommends for photographic noise.
bool applyDenoise(const cv::Mat& bgra, cv::Mat& out, double strength) {
    cv::Mat bgr;
    cv::cvtColor(bgra, bgr, cv::COLOR_BGRA2BGR);

    const float h = static_cast<float>(3.0 + 12.0 * strength);
    cv::Mat denoised;
    cv::fastNlMeansDenoisingColored(bgr, denoised, h, h, 7, 21);

    cv::cvtColor(denoised, out, cv::COLOR_BGR2BGRA);
    return true;
}

/// Super-resolution, then a resize back to the original size.
///
/// The SPI contract is that `enhance` returns an array of the same length, so an
/// upscaler has to come back down. That sounds pointless and is not: a 2x DNN
/// upscale followed by a bilinear downscale is a well-known way to recover
/// detail an ordinary sharpen cannot invent. A real geometry change belongs in a
/// separate non-tileable ImageOperation with a declared output size, which is
/// what NativeImageEnhancer.enhance() says when it rejects a length mismatch.
bool applySuperResolution(const cv::Mat& bgra, cv::Mat& out, double strength) {
#ifdef PIP_WITH_DNN_SUPERRES
    if (!g_model_ready) {
        return false;
    }
    cv::Mat bgr;
    cv::cvtColor(bgra, bgr, cv::COLOR_BGRA2BGR);

    cv::Mat upscaled;
    g_super_res.upsample(bgr, upscaled);

    cv::Mat back;
    cv::resize(upscaled, back, bgr.size(), 0, 0, cv::INTER_AREA);

    cv::Mat blended;
    cv::addWeighted(back, strength, bgr, 1.0 - strength, 0.0, blended);

    cv::cvtColor(blended, out, cv::COLOR_BGR2BGRA);
    return true;
#else
    // Built without the contrib module. Returning false becomes a null return,
    // which the Java side treats as "not implemented here" and logs at DEBUG.
    (void)bgra;
    (void)out;
    (void)strength;
    return false;
#endif
}

}  // namespace

extern "C" {

JNIEXPORT jint JNICALL
Java_com_parallelimage_nativebridge_NativeImageEnhancer_nativeApiVersion(JNIEnv*, jclass) {
    return kApiVersion;
}

JNIEXPORT jstring JNICALL
Java_com_parallelimage_nativebridge_NativeImageEnhancer_nativeDescribe(JNIEnv* env, jclass) {
    std::string description = CV_VERSION;
#ifdef PIP_WITH_DNN_SUPERRES
    description += " +dnn_superres";
#endif
    return env->NewStringUTF(description.c_str());
}

JNIEXPORT jboolean JNICALL
Java_com_parallelimage_nativebridge_NativeImageEnhancer_nativeSupports(JNIEnv*, jclass,
                                                                      jint mode_code) {
    switch (mode_code) {
        case kCodeClahe:
        case kCodeDenoise:
            return JNI_TRUE;
        case kCodeSuperResolution:
#ifdef PIP_WITH_DNN_SUPERRES
            return JNI_TRUE;
#else
            return JNI_FALSE;
#endif
        default:
            return JNI_FALSE;
    }
}

JNIEXPORT jboolean JNICALL
Java_com_parallelimage_nativebridge_NativeImageEnhancer_nativeLoadModel(JNIEnv* env, jclass,
                                                                       jstring model_path) {
#ifdef PIP_WITH_DNN_SUPERRES
    std::string path;
    if (model_path != nullptr) {
        const char* utf = env->GetStringUTFChars(model_path, nullptr);
        if (utf != nullptr) {
            path.assign(utf);
            env->ReleaseStringUTFChars(model_path, utf);
        }
    }
    if (path.empty()) {
        return JNI_FALSE;  // no default bundled; the Java side tells the user how to set one
    }

    // call_once even though the Java side already serialises with a
    // ManagedBlocker: this entry point is public C ABI, and a second caller
    // (a future CLI diagnostic, a test harness) must not be able to reload the
    // model underneath a batch that is mid-upsample.
    std::call_once(g_model_once, [&path]() {
        try {
            g_super_res.readModel(path);
            // EDSR x2 is the default assumption; a model whose filename encodes
            // something else will fail here rather than produce garbage.
            g_super_res.setModel("edsr", 2);
            g_model_ready = true;
        } catch (const cv::Exception&) {
            g_model_ready = false;
        }
    });
    return g_model_ready ? JNI_TRUE : JNI_FALSE;
#else
    (void)env;
    (void)model_path;
    return JNI_FALSE;
#endif
}

JNIEXPORT jobject JNICALL
Java_com_parallelimage_nativebridge_NativeImageEnhancer_nativeEnhance(JNIEnv* env, jclass,
                                                                     jobject argb, jobject out_buffer,
                                                                     jint width, jint height,
                                                                     jint mode_code,
                                                                     jdouble strength) {
    if (argb == nullptr || out_buffer == nullptr || width <= 0 || height <= 0) {
        return nullptr;
    }
    const int64_t pixel_count = static_cast<int64_t>(width) * static_cast<int64_t>(height);
    if (pixel_count > kMaxPixels) {
        return nullptr;
    }
    const int64_t expected_bytes = pixel_count * 4;

    // The Java side promises both buffers are direct and exactly width * height * 4
    // bytes. Verify it anyway: this is the boundary where a wrong promise stops
    // being a bug and becomes an out-of-bounds read or write.
    if (env->GetDirectBufferCapacity(argb) != expected_bytes
        || env->GetDirectBufferCapacity(out_buffer) != expected_bytes) {
        return nullptr;
    }

    // GetDirectBufferAddress: a raw pointer into memory the JVM never moves and
    // never garbage-collects out from under us. Unlike GetPrimitiveArrayCritical
    // this carries no ban on JNI calls or allocations while held, so it is fine to
    // keep it for the whole call rather than releasing it before doing OpenCV work.
    void* in_address = env->GetDirectBufferAddress(argb);
    void* out_address = env->GetDirectBufferAddress(out_buffer);
    if (in_address == nullptr || out_address == nullptr) {
        return nullptr;
    }

    cv::Mat result;
    bool ok = false;
    try {
        const cv::Mat source = wrapArgb(static_cast<jint*>(in_address), width, height);
        switch (mode_code) {
            case kCodeClahe:
                ok = applyClahe(source, result, strength);
                break;
            case kCodeDenoise:
                ok = applyDenoise(source, result, strength);
                break;
            case kCodeSuperResolution:
                ok = applySuperResolution(source, result, strength);
                break;
            default:
                ok = false;
                break;
        }
    } catch (const cv::Exception&) {
        ok = false;
    } catch (...) {
        // std::bad_alloc from a large intermediate, most likely. Swallowed for
        // the same reason as everything else here: an exception must not
        // propagate into the JVM's stack frames.
        ok = false;
    }

    if (!ok || result.empty() || !result.isContinuous() || result.type() != CV_8UC4
        || result.total() != static_cast<size_t>(pixel_count)) {
        return nullptr;
    }

    std::memcpy(out_address, result.data, static_cast<size_t>(expected_bytes));
    return out_buffer;
}

}  // extern "C"
