server:
  port: 8084

spring:
  application:
    name: entity-linking-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.ehrplatform: DEBUG
