{{- if .Values.metrics.serviceMonitor.enabled }}
# Prometheus Operator scrape config — pairs with kube-prometheus-stack.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "order-service.fullname" . }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "order-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
