// ML and Analytics Type Definitions

export interface DataPoint {
  timestamp: string | number;
  value: number;
  metadata?: Record<string, any>;
}

export interface TimeSeries {
  id: string;
  name: string;
  data: DataPoint[];
  interval?: 'minute' | 'hour' | 'day' | 'week' | 'month';
  unit?: string;
  description?: string;
}

export interface Anomaly {
  id: string;
  timestamp: string | number;
  value: number;
  expectedValue: number;
  severity: 'low' | 'medium' | 'high' | 'critical';
  score: number; // 0-1, higher = more anomalous
  type: 'spike' | 'dip' | 'trend_change' | 'seasonal_deviation' | 'outlier';
  description: string;
  metadata?: Record<string, any>;
}

export interface Forecast {
  id: string;
  seriesId: string;
  predictions: DataPoint[];
  confidence: number; // 0-1
  horizon: number; // number of periods forecasted
  model: string;
  createdAt: string;
  accuracy?: number;
  metadata?: Record<string, any>;
}

export interface Insight {
  id: string;
  type: 'trend' | 'anomaly' | 'correlation' | 'seasonality' | 'recommendation';
  title: string;
  description: string;
  severity: 'info' | 'warning' | 'critical';
  confidence: number; // 0-1
  timestamp: string;
  data?: any;
  actions?: InsightAction[];
  isRead?: boolean;
}

export interface InsightAction {
  id: string;
  label: string;
  type: 'link' | 'action' | 'dismiss';
  url?: string;
  action?: string;
  parameters?: Record<string, any>;
}

export interface PatternAnalysis {
  id: string;
  seriesId: string;
  patterns: DetectedPattern[];
  createdAt: string;
}

export interface DetectedPattern {
  type: 'trend' | 'seasonal' | 'cyclical' | 'irregular';
  description: string;
  strength: number; // 0-1
  period?: number; // for seasonal patterns
  direction?: 'increasing' | 'decreasing' | 'stable'; // for trends
  startDate?: string;
  endDate?: string;
  confidence: number;
}

export interface CorrelationAnalysis {
  id: string;
  series1Id: string;
  series2Id: string;
  coefficient: number; // -1 to 1
  pValue: number;
  significance: 'not_significant' | 'weak' | 'moderate' | 'strong' | 'very_strong';
  lag?: number; // time lag if cross-correlation
  createdAt: string;
}

export interface MLModelConfig {
  type: 'anomaly_detection' | 'forecasting' | 'classification' | 'clustering';
  algorithm: string;
  parameters: Record<string, any>;
  trainingData?: TimeSeries[];
  features?: string[];
  target?: string;
  validationSplit?: number;
}

export interface MLModel {
  id: string;
  name: string;
  type: MLModelConfig['type'];
  status: 'training' | 'trained' | 'failed' | 'deployed';
  accuracy?: number;
  config: MLModelConfig;
  createdAt: string;
  updatedAt: string;
  version: string;
  metrics?: Record<string, number>;
}

export interface AlertRule {
  id: string;
  name: string;
  seriesId: string;
  condition: AlertCondition;
  isActive: boolean;
  recipients: string[];
  channels: ('email' | 'sms' | 'webhook' | 'dashboard')[];
  createdAt: string;
  lastTriggered?: string;
}

export interface AlertCondition {
  type: 'threshold' | 'anomaly' | 'trend' | 'forecast_deviation';
  operator?: '>' | '<' | '>=' | '<=' | '==' | '!=';
  value?: number;
  window?: number; // time window in minutes
  sensitivity?: 'low' | 'medium' | 'high';
  metadata?: Record<string, any>;
}

export interface Alert {
  id: string;
  ruleId: string;
  timestamp: string;
  severity: 'info' | 'warning' | 'critical';
  title: string;
  description: string;
  value: number;
  isResolved: boolean;
  resolvedAt?: string;
  resolvedBy?: string;
  metadata?: Record<string, any>;
}

export interface AnalyticsReport {
  id: string;
  title: string;
  description: string;
  type: 'summary' | 'detailed' | 'comparison' | 'forecast';
  seriesIds: string[];
  period: {
    start: string;
    end: string;
  };
  insights: Insight[];
  charts: ReportChart[];
  tables: ReportTable[];
  createdAt: string;
  createdBy: string;
  isAutoGenerated: boolean;
}

export interface ReportChart {
  id: string;
  type: 'line' | 'bar' | 'area' | 'scatter' | 'heatmap';
  title: string;
  data: any[];
  config: Record<string, any>;
}

export interface ReportTable {
  id: string;
  title: string;
  columns: Array<{
    key: string;
    title: string;
    type: 'string' | 'number' | 'date' | 'boolean';
    formatter?: string;
  }>;
  data: Record<string, any>[];
}

// Utility types
export type TimeRange = {
  start: string | number;
  end: string | number;
};

export type AggregationType = 'sum' | 'avg' | 'min' | 'max' | 'count' | 'median' | 'std';

export type SeasonalityType = 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'yearly';

// Error types
export class MLError extends Error {
  code: string;
  details?: any;
  timestamp: string;

  constructor(params: { code: string; message: string; details?: any; timestamp: string }) {
    super(params.message);
    this.name = 'MLError';
    this.code = params.code;
    this.details = params.details;
    this.timestamp = params.timestamp;
  }
}
