name: habit_streak_tracker
description: "Habit Streak Tracker with SQLite, Riverpod, Local Notifications, and Home Widgets"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  home_widget: ^0.7.0
  timezone: ^0.9.4
  uuid: ^4.5.1
  intl: ^0.20.2
  sqflite_common_ffi_web: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
