-- V1 baseline schema for fhir-gateway-service (Oracle).
-- Owned exclusively by this service. Backward-compatible (expand-then-contract).

-- Searchable projection + raw FHIR resource store for Patient.
CREATE TABLE PATIENT_INDEX (
    FHIR_ID           VARCHAR2(64)   NOT NULL,
    IDENTIFIER_SYSTEM VARCHAR2(256),
    IDENTIFIER_VALUE  VARCHAR2(256),
    FAMILY_NAME       VARCHAR2(256),
    GIVEN_NAME        VARCHAR2(256),
    BIRTH_DATE        DATE,
    RESOURCE_JSON     CLOB,
    LAST_UPDATED      TIMESTAMP      NOT NULL,
    VERSION           NUMBER(19)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PATIENT_INDEX PRIMARY KEY (FHIR_ID)
);

-- Backs FHIR search: GET /fhir/Patient?identifier=system|value
CREATE INDEX IX_PATIENT_IDENTIFIER ON PATIENT_INDEX (IDENTIFIER_SYSTEM, IDENTIFIER_VALUE);
CREATE INDEX IX_PATIENT_FAMILY ON PATIENT_INDEX (FAMILY_NAME);

-- Observation projection + raw resource store.
CREATE TABLE OBSERVATION_INDEX (
    FHIR_ID       VARCHAR2(64)  NOT NULL,
    PATIENT_ID    VARCHAR2(64),
    CODE_SYSTEM   VARCHAR2(256),
    CODE_VALUE    VARCHAR2(64),
    STATUS        VARCHAR2(32),
    EFFECTIVE_AT  TIMESTAMP,
    RESOURCE_JSON CLOB,
    LAST_UPDATED  TIMESTAMP     NOT NULL,
    VERSION       NUMBER(19)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_OBSERVATION_INDEX PRIMARY KEY (FHIR_ID)
);
CREATE INDEX IX_OBS_PATIENT ON OBSERVATION_INDEX (PATIENT_ID);
CREATE INDEX IX_OBS_CODE ON OBSERVATION_INDEX (CODE_SYSTEM, CODE_VALUE);

-- Encounter projection + raw resource store.
CREATE TABLE ENCOUNTER_INDEX (
    FHIR_ID       VARCHAR2(64)  NOT NULL,
    PATIENT_ID    VARCHAR2(64),
    STATUS        VARCHAR2(32),
    CLASS_CODE    VARCHAR2(32),
    PERIOD_START  TIMESTAMP,
    PERIOD_END    TIMESTAMP,
    RESOURCE_JSON CLOB,
    LAST_UPDATED  TIMESTAMP     NOT NULL,
    VERSION       NUMBER(19)    DEFAULT 0 NOT NULL,
    CONSTRAINT PK_ENCOUNTER_INDEX PRIMARY KEY (FHIR_ID)
);
CREATE INDEX IX_ENC_PATIENT ON ENCOUNTER_INDEX (PATIENT_ID);

-- Transactional outbox: written in the same TX as the resource change,
-- drained to Kafka by the relay (at-least-once, no dual-write).
CREATE TABLE OUTBOX_EVENT (
    EVENT_ID       VARCHAR2(64)  NOT NULL,
    EVENT_TYPE     VARCHAR2(128) NOT NULL,
    RESOURCE_TYPE  VARCHAR2(64)  NOT NULL,
    RESOURCE_ID    VARCHAR2(64)  NOT NULL,
    PAYLOAD_JSON   CLOB          NOT NULL,
    CREATED_AT     TIMESTAMP     NOT NULL,
    SENT_AT        TIMESTAMP,
    CONSTRAINT PK_OUTBOX_EVENT PRIMARY KEY (EVENT_ID)
);

-- Relay scans for unsent rows oldest-first.
CREATE INDEX IX_OUTBOX_UNSENT ON OUTBOX_EVENT (SENT_AT, CREATED_AT);

-- Append-only PHI access audit (HIPAA accounting of disclosures, retain >= 6y).
CREATE TABLE PHI_AUDIT (
    AUDIT_ID       VARCHAR2(64)  NOT NULL,
    ACTOR_ID       VARCHAR2(256) NOT NULL,
    ACTION         VARCHAR2(32)  NOT NULL,
    RESOURCE_TYPE  VARCHAR2(64)  NOT NULL,
    RESOURCE_ID    VARCHAR2(64),
    PURPOSE_OF_USE VARCHAR2(64),
    SOURCE_IP      VARCHAR2(64),
    OCCURRED_AT    TIMESTAMP     NOT NULL,
    TRACE_ID       VARCHAR2(64),
    CONSTRAINT PK_PHI_AUDIT PRIMARY KEY (AUDIT_ID)
);
CREATE INDEX IX_AUDIT_RESOURCE ON PHI_AUDIT (RESOURCE_TYPE, RESOURCE_ID);
CREATE INDEX IX_AUDIT_ACTOR ON PHI_AUDIT (ACTOR_ID, OCCURRED_AT);
